feat: add EL10 IPv6-only provisioning support

diff --git a/xCAT-server/share/xcat/netboot/rh/dracut_105/stateless/xcatroot b/xCAT-server/share/xcat/netboot/rh/dracut_105/stateless/xcatroot
--- a/xCAT-server/share/xcat/netboot/rh/dracut_105/stateless/xcatroot
+++ b/xCAT-server/share/xcat/netboot/rh/dracut_105/stateless/xcatroot
@@ -1,4 +1,115 @@
 #!/bin/bash
+
+xcat_endpoint_host() {
+    local endpoint="$1"
+    local host
+    local remainder
+
+    case "$endpoint" in
+        \[*\]:*)
+            host=${endpoint#\[}
+            host=${host%%\]*}
+            ;;
+        \[*\])
+            host=${endpoint#\[}
+            host=${host%\]}
+            ;;
+        *:*)
+            remainder=${endpoint#*:}
+            if [[ "$remainder" == *:* ]]; then
+                # An unbracketed IPv6 literal has no unambiguous port suffix.
+                host=$endpoint
+            else
+                host=${endpoint%%:*}
+            fi
+            ;;
+        *)
+            host=$endpoint
+            ;;
+    esac
+
+    [ -n "$host" ] || return 1
+    printf '%s\n' "$host"
+}
+
+xcat_is_ipv6_boot() {
+    local iparg="$1"
+    local netif="$2"
+
+    case "$iparg" in
+        dhcp6|*:dhcp6|*:dhcp6:*)
+            return 0
+            ;;
+    esac
+
+    [ -n "$netif" ] || return 1
+    ip -6 -o addr show dev "$netif" scope global 2>/dev/null | grep -q . || return 1
+    ! ip -4 -o addr show dev "$netif" scope global 2>/dev/null | grep -q .
+}
+
+persist_ipv6_nm_connection() {
+    local newroot="$1"
+    local netif="$2"
+    local mac="$3"
+    shift 3
+
+    local destination="$newroot/etc/NetworkManager/system-connections"
+    local source
+    local profile
+    local copied=0
+    local address_cidr
+    local gateway
+    local sources=("$@")
+
+    if [ ${#sources[@]} -eq 0 ]; then
+        sources=(
+            /run/NetworkManager/system-connections
+            /etc/NetworkManager/system-connections
+        )
+    fi
+
+    mkdir -p "$destination"
+    for source in "${sources[@]}"; do
+        [ -d "$source" ] || continue
+        for profile in "$source"/*.nmconnection; do
+            [ -f "$profile" ] || continue
+            cp -p "$profile" "$destination/"
+            chmod 600 "$destination/${profile##*/}"
+            copied=1
+        done
+    done
+
+    if [ "$copied" -eq 0 ]; then
+        address_cidr=$(ip -6 -o addr show dev "$netif" scope global 2>/dev/null |
+            awk '$3 == "inet6" { print $4; exit }')
+        [ -n "$address_cidr" ] || return 1
+        gateway=$(ip -6 route show default dev "$netif" 2>/dev/null |
+            awk '$1 == "default" && $2 == "via" { print $3; exit }')
+
+        profile="$destination/xcat-$netif.nmconnection"
+        cat > "$profile" <<EOF
+[connection]
+id=xcat-$netif
+type=ethernet
+interface-name=$netif
+autoconnect=true
+
+[ethernet]
+mac-address=$mac
+
+[ipv4]
+method=disabled
+
+[ipv6]
+method=manual
+address1=$address_cidr
+gateway=$gateway
+addr-gen-mode=default
+EOF
+        chmod 600 "$profile"
+    fi
+}
+
 log_label="xcat.deployment"
 
 NEWROOT=$3
@@ -14,35 +125,35 @@ rflags="$(getarg rootflags=)"
 getarg nonodestatus
 NODESTATUS=$?
 
-MASTER=`echo $XCATMASTER |awk -F: '{print $1}'`
+MASTER="$(xcat_endpoint_host "$XCATMASTER")"
 XCATIPORT="$(getarg XCATIPORT=)"
 if [ $? -ne 0 ]; then
     XCATIPORT="3002"
 fi
 
-[ "$xcatdebugmode" = "1" -o "$xcatdebugmode" = "2" ] && SYSLOGHOST="" || SYSLOGHOST="-n $MASTER"
-logger $SYSLOGHOST -t $log_label -p local4.info "=============deployment starting===================="
-logger $SYSLOGHOST -t $log_label -p local4.info "Executing xcatroot to prepare for netbooting (dracut_33)..."
+[ "$xcatdebugmode" = "1" -o "$xcatdebugmode" = "2" ] && SYSLOGHOST=() || SYSLOGHOST=(-n "$MASTER")
+logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "=============deployment starting===================="
+logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Executing xcatroot to prepare for netbooting (dracut_33)..."
 [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "MASTER=$MASTER XCATIPORT=$XCATIPORT NODESTATUS=$NODESTATUS"
 
 if [ "$NODESTATUS" != "0" ]; then
-    logger $SYSLOGHOST -t $log_label -p local4.info "Sending request to $MASTER:$XCATIPORT for changing status to netbooting..."
-    /tmp/updateflag $MASTER $XCATIPORT "installstatus netbooting"
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Sending request to $MASTER:$XCATIPORT for changing status to netbooting..."
+    /tmp/updateflag "$MASTER" "$XCATIPORT" "installstatus netbooting"
 fi
 
 
 imgurl="$(getarg imgurl=)";
 if [ ! -z "$imgurl" ]; then
     if [ xhttp = x${imgurl%%:*} ]; then
-        logger $SYSLOGHOST -t $log_label -p local4.info "Downloading rootfs image from $imgurl..."
+        logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Downloading rootfs image from $imgurl..."
         NFS=0
         FILENAME=${imgurl##*/}
         while [ ! -r "$FILENAME" ]; do
             [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Downloading $imgurl..."
-            echo Getting $imgurl...
-            if ! curl --fail $imgurl -o $FILENAME; then
-                logger $SYSLOGHOST -t $log_label -p local4.error "Downloading $imgurl FAILED, retrying..."
-                rm -f $FILENAME
+            echo "Getting $imgurl..."
+            if ! curl --fail --output "$FILENAME" -- "$imgurl"; then
+                logger "${SYSLOGHOST[@]}" -t $log_label -p local4.error "Downloading $imgurl FAILED, retrying..."
+                rm -f "$FILENAME"
                 echo Failed to get the image, waiting for next retrying...
                 sleep 27
             fi
@@ -84,7 +195,7 @@ if [ -r /rootimg.sfs ]; then
         mount --move /rw $NEWROOT/rw
     fi
 elif [ -r /rootimg.cpio.gz ] || [ -r /rootimg.cpio.xz ]; then
-    logger $SYSLOGHOST -t $log_label -p local4.info "Setting up RAM-root tmpfs on downloaded rootimg.cpio.[gz/xz]..."
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Setting up RAM-root tmpfs on downloaded rootimg.cpio.[gz/xz]..."
     echo Setting up RAM-root tmpfs.
     rootopts="mode=755"
     if [ -n "$rflags" ]; then
@@ -116,7 +227,7 @@ elif [ -r /rootimg.cpio.gz ] || [ -r /rootimg.cpio.xz ]; then
     [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Done extracting the root filesystem..."
     echo "Done extracting the root filesystem..."
 elif [ -r /rootimg.tar.gz ] || [ -r /rootimg.tar.xz ]; then
-    logger $SYSLOGHOST -t $log_label -p local4.info "Setting up RAM-root tmpfs on downloaded rootimg.tar.[gz/xz]..."
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Setting up RAM-root tmpfs on downloaded rootimg.tar.[gz/xz]..."
     echo Setting up RAM-root tmpfs.
     if [ -z $rootlimit ];then
         mount -t tmpfs -o mode=755 rootfs $NEWROOT
@@ -144,7 +255,7 @@ elif [ -r /rootimg.tar.gz ] || [ -r /rootimg.tar.xz ]; then
     echo "$msg"
 elif [ -r /rootimg-statelite.gz ]; then
     msg="Setting up RAM-root tmpfs for statelite mode."
-    logger $SYSLOGHOST -t $log_label -p local4.info "$msg"
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "$msg"
     echo "$msg"
 
     if [ -z $rootlimit];then
@@ -177,7 +288,7 @@ elif [ -r /rootimg-statelite.gz ]; then
         echo ""
         echo "The /$RWDIR directory doesn't exist in the rootimg... "
         echo ""
-        logger $SYSLOGHOST -t $log_label -p local4.err "The /$RWDIR directory doesn't exist in the rootimg..."
+        logger "${SYSLOGHOST[@]}" -t $log_label -p local4.err "The /$RWDIR directory doesn't exist in the rootimg..."
         /bin/sh
     fi
 
@@ -185,7 +296,7 @@ elif [ -r /rootimg-statelite.gz ]; then
         echo ""
         echo "$NEWROOT/etc/init.d/statelite doesn't exist... "
         echo ""
-        logger $SYSLOGHOST -t $log_label -p local4.err "$NEWROOT/etc/init.d/statelite doesn't exist... " 
+        logger "${SYSLOGHOST[@]}" -t $log_label -p local4.err "$NEWROOT/etc/init.d/statelite doesn't exist... "
         /bin/sh
     fi
 
@@ -224,7 +335,7 @@ elif [ -r /rootimg-statelite.gz ]; then
     1.  $SNAPSHOTSERVER is not exporting $SNAPSHOTROOT ?
     2.  Is DNS set up? Maybe that's why I can't mount $SNAPSHOTSERVER."
                 echo "$msg"
-                logger $SYSLOGHOST -t $log_label -p local4.err "$msg"
+                logger "${SYSLOGHOST[@]}" -t $log_label -p local4.err "$msg"
                 /bin/sh
                 exit
             fi
@@ -243,7 +354,7 @@ elif [ -r /rootimg-statelite.gz ]; then
                 msg="Your are dead, rpower $ME boot to play again.
                      Cannot umount $NEWROOT/$RWDIR/persistent."
                 echo "$msg"
-                logger $SYSLOGHOST -t $log_label -p local4.err "$msg"
+                logger "${SYSLOGHOST[@]}" -t $log_label -p local4.err "$msg"
                 /bin/sh
                 exit
             fi
@@ -260,7 +371,7 @@ elif [ -r /rootimg-statelite.gz ]; then
                 msg="Your are dead, rpower $ME boot to play again.
                      Possible problems: cannot mount to $SNAPSHOTSERVER:/$SNAPSHOTROOT/$ME."
                 echo "$msg"
-                logger $SYSLOGHOST -t $log_label -p local4.err "$msg"
+                logger "${SYSLOGHOST[@]}" -t $log_label -p local4.err "$msg"
                 /bin/sh
                 exit
             fi
@@ -270,9 +381,9 @@ elif [ -r /rootimg-statelite.gz ]; then
         done
     fi
 
-    logger $SYSLOGHOST -t $log_label -p local4.info "Enabling localdisk ..."
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Enabling localdisk ..."
     $NEWROOT/etc/init.d/localdisk
-    logger $SYSLOGHOST -t $log_label -p local4.info "Preparing mount points ..."
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Preparing mount points ..."
     $NEWROOT/etc/init.d/statelite
     fastboot=yes
     export fastboot
@@ -285,7 +396,7 @@ elif [ -r /rootimg-statelite.gz ]; then
 
 else
     msg="Failed to download image, panic in 5..."
-    logger $SYSLOGHOST -t $log_label -p local4.error "$msg"
+    logger "${SYSLOGHOST[@]}" -t $log_label -p local4.error "$msg"
     echo -n "$msg"
     for i in 4 3 2 1 0; do
         /bin/sleep 1
@@ -332,7 +443,7 @@ function getdevfrommac() {
 }
 
 
-if [ -z $STATEMNT ]; then
+if [ -z "$STATEMNT" ]; then
     for lf in /tmp/dhclient.*.lease; do
         netif=${lf#*.}
         netif=${netif%.*}
@@ -357,16 +468,34 @@ if [ -z $STATEMNT ]; then
     fi
 
 
-    if [ ! -z "$MACX" ] && [ ! -z "$ETHX" ]; then
-        if [ ! -e $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX ]; then
-            [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Creating $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
-            touch $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX
+    if [ -n "$MACX" ] && [ -n "$ETHX" ]; then
+        BOOT_IP="$(getarg ip=)"
+        IPV6_BOOT=0
+        if xcat_is_ipv6_boot "$BOOT_IP" "$ETHX"; then
+            IPV6_BOOT=1
+            [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Persisting the NetworkManager connection for IPv6 interface $ETHX"
+            if ! persist_ipv6_nm_connection "$NEWROOT" "$ETHX" "$MACX"; then
+                logger -t $log_label -p local4.error "Unable to persist the static IPv6 configuration for $ETHX"
+                exit 1
+            fi
         fi
-        [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Writing $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX: DEVICE=$ETHX;BOOTPROTO=dhcp;HWADDR=$MACX;ONBOOT=yes"
-        echo "DEVICE=$ETHX" > $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX
-        echo "BOOTPROTO=dhcp" >> $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX
-        echo "HWADDR=$MACX" >> $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX
-        echo "ONBOOT=yes" >> $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX
+
+        if [ "$IPV6_BOOT" -eq 1 ]; then
+            # EL10 uses NetworkManager keyfiles.  Do not leave a competing
+            # legacy ifcfg profile that would start a new DHCPv6 identity.
+            rm -f "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+        else
+            if [ ! -e "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX" ]; then
+                [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Creating $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+                mkdir -p "$NEWROOT/etc/sysconfig/network-scripts"
+                touch "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+            fi
+            [ "$xcatdebugmode" > "0" ] && logger -t $log_label -p local4.debug "Writing $NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX: DEVICE=$ETHX;BOOTPROTO=dhcp;HWADDR=$MACX;ONBOOT=yes"
+            echo "DEVICE=$ETHX" > "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+            echo "BOOTPROTO=dhcp" >> "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+            echo "HWADDR=$MACX" >> "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+            echo "ONBOOT=yes" >> "$NEWROOT/etc/sysconfig/network-scripts/ifcfg-$ETHX"
+        fi
     fi
 fi
 
@@ -378,7 +507,7 @@ if [ -d "$NEWROOT/etc/sysconfig" -a ! -e "$NEWROOT/etc/sysconfig/selinux" ]; the
     echo "SELINUX=disabled" >> "$NEWROOT/etc/sysconfig/selinux"
 fi
 
-logger $SYSLOGHOST -t $log_label -p local4.info "Exiting xcatroot..."
+logger "${SYSLOGHOST[@]}" -t $log_label -p local4.info "Exiting xcatroot..."
 # inject new exit_if_exists
 echo 'settle_exit_if_exists="--exit-if-exists=/dev/root"; rm "$job"' > $hookdir/initqueue/xcat.sh
 # force udevsettle to break
diff --git a/xCAT/postscripts/configeth b/xCAT/postscripts/configeth
--- a/xCAT/postscripts/configeth
+++ b/xCAT/postscripts/configeth
@@ -40,6 +40,153 @@ fi
 str_conf_file=""
 str_conf_file_xcatbak=""
 tmp_con_name=""
+
+# Capture the active IPv6 configuration of an install NIC before replacing the
+# installer-created NetworkManager connection.  DHCPv6 leases are not recorded
+# in the legacy dhclient lease format used by the IPv4 path below, so use the
+# kernel and NetworkManager runtime state as the source of truth.
+function discover_install_nic_ipv6(){
+    local str_if_name=$1
+    local str_preferred_addr=${2:-}
+    local str_addr_cidr
+
+    str_addr_cidr=`ip -6 -o addr show dev "$str_if_name" scope global 2>/dev/null | awk -v preferred="$str_preferred_addr" '
+        $3 == "inet6" {
+            unusable = 0
+            for (i = 5; i <= NF; i++) {
+                if ($i == "temporary" || $i == "tentative" ||
+                    $i == "deprecated" || $i == "dadfailed") {
+                    unusable = 1
+                }
+            }
+            if (!unusable) {
+                split($4, addr, "/")
+                if (preferred && addr[1] == preferred) {
+                    print $4
+                    found = 1
+                    exit
+                }
+                if (!candidate) candidate = $4
+            }
+        }
+        END { if (!found && candidate) print candidate }'`
+
+    [ -z "$str_addr_cidr" ] && return 1
+
+    str_inst_ipv6=${str_addr_cidr%/*}
+    str_inst_ipv6_prefix=${str_addr_cidr##*/}
+    str_inst_ipv6_gateway=`ip -6 route show default dev "$str_if_name" 2>/dev/null | awk '$1 == "default" && $2 == "via" { print $3; exit }'`
+    str_inst_mtu=`ip -o link show dev "$str_if_name" 2>/dev/null | awk '{ for (i = 1; i <= NF; i++) if ($i == "mtu") { print $(i + 1); exit } }'`
+
+    if command -v nmcli >/dev/null 2>&1; then
+        if [ -z "$str_inst_ipv6_gateway" ]; then
+            str_inst_ipv6_gateway=`nmcli --escape no -g IP6.GATEWAY device show "$str_if_name" 2>/dev/null | awk 'NF && $0 != "--" { print; exit }'`
+        fi
+        str_inst_ipv6_dns=`nmcli --escape no -g IP6.DNS device show "$str_if_name" 2>/dev/null | awk '
+            NF && $0 != "--" && index($0, ":") {
+                if (dns) dns = dns "," $0
+                else dns = $0
+            }
+            END { print dns }'`
+        str_inst_ipv6_dns_search=`nmcli --escape no -g IP6.SEARCHES device show "$str_if_name" 2>/dev/null | awk '
+            NF && $0 != "--" {
+                if (search) search = search "," $0
+                else search = $0
+            }
+            END { print search }'`
+    fi
+
+    # NetworkManager's runtime resolv.conf is a useful fallback when the device
+    # did not receive DNS information directly (for example, DNS supplied by a
+    # local resolver or another RA/DHCPv6 component).
+    if [ -z "$str_inst_ipv6_dns" ] && [ -f /var/run/NetworkManager/resolv.conf ]; then
+        str_inst_ipv6_dns=`awk '
+            $1 == "nameserver" && index($2, ":") {
+                if (dns) dns = dns "," $2
+                else dns = $2
+            }
+            END { print dns }' /var/run/NetworkManager/resolv.conf`
+    fi
+    if [ -z "$str_inst_ipv6_dns_search" ] && [ -f /var/run/NetworkManager/resolv.conf ]; then
+        str_inst_ipv6_dns_search=`awk '$1 == "search" { $1 = ""; sub(/^ /, ""); gsub(/ +/, ","); print; exit }' /var/run/NetworkManager/resolv.conf`
+    fi
+
+    return 0
+}
+
+# Persist an IPv6-only install connection as a native NetworkManager keyfile.
+# Keeping this separate from configipv6 preserves the existing static-address
+# path while allowing configeth -s to replace an installer DHCPv6 connection.
+function configure_install_nic_ipv6_nm(){
+    local str_con_name=$1
+    local str_if_name=$2
+    local str_v6ip=$3
+    local str_v6prefix=$4
+    local str_v6gateway=$5
+    local str_v6dns=$6
+    local str_v6dns_search=$7
+    local str_nic_mtu=$8
+    local -a nm_args=(
+        con add type ethernet
+        con-name "$str_con_name"
+        ifname "$str_if_name"
+        ipv4.method disabled
+        ipv6.method manual
+        ipv6.addresses "${str_v6ip}/${str_v6prefix}"
+        connection.autoconnect yes
+        connection.autoconnect-priority 9
+    )
+
+    [ -n "$str_v6gateway" ] && nm_args+=(ipv6.gateway "$str_v6gateway")
+    [ -n "$str_v6dns" ] && nm_args+=(ipv6.dns "$str_v6dns")
+    [ -n "$str_v6dns_search" ] && nm_args+=(ipv6.dns-search "$str_v6dns_search")
+    [ -n "$str_nic_mtu" ] && nm_args+=(802-3-ethernet.mtu "$str_nic_mtu")
+
+    nmcli "${nm_args[@]}"
+}
+
+# During Anaconda's chrooted %post, NetworkManager is running but nmcli cannot
+# persist a connection in the target root.  Write the equivalent native
+# keyfile there so the IPv6-only install NIC is selected on first boot.
+function configure_install_nic_ipv6_keyfile(){
+    local str_con_name=$1
+    local str_if_name=$2
+    local str_v6ip=$3
+    local str_v6prefix=$4
+    local str_v6gateway=$5
+    local str_v6dns=$6
+    local str_v6dns_search=$7
+    local str_nic_mtu=$8
+    local str_keyfile=$9
+    local str_keyfile_dir=${str_keyfile%/*}
+    local str_tmp_keyfile="${str_keyfile}.xcat.$$"
+    local -a nm_args=(
+        con add type ethernet
+        con-name "$str_con_name"
+        ifname "$str_if_name"
+        ipv4.method disabled
+        ipv6.method manual
+        ipv6.addresses "${str_v6ip}/${str_v6prefix}"
+        connection.autoconnect yes
+        connection.autoconnect-priority 9
+    )
+
+    [ -n "$str_v6gateway" ] && nm_args+=(ipv6.gateway "$str_v6gateway")
+    [ -n "$str_v6dns" ] && nm_args+=(ipv6.dns "$str_v6dns")
+    [ -n "$str_v6dns_search" ] && nm_args+=(ipv6.dns-search "$str_v6dns_search")
+    [ -n "$str_nic_mtu" ] && nm_args+=(802-3-ethernet.mtu "$str_nic_mtu")
+
+    mkdir -p "$str_keyfile_dir" || return $?
+    (
+        umask 077
+        LC_ALL=C nmcli --offline "${nm_args[@]}" > "$str_tmp_keyfile" &&
+            mv -f "$str_tmp_keyfile" "$str_keyfile"
+    )
+    local int_rc=$?
+    [ $int_rc -ne 0 ] && rm -f "$str_tmp_keyfile"
+    return $int_rc
+}
+
 function configipv4(){
     str_if_name=$1
     str_v4ip=$2
@@ -564,6 +711,15 @@ elif [ "$1" = "-s" ];then
     str_inst_gateway=''
     str_inst_mtu=''
     str_inst_dns=''
+    str_inst_dns_search=''
+    str_inst_ipv6=''
+    str_inst_ipv6_prefix=''
+    str_inst_ipv6_gateway=''
+    str_inst_ipv6_dns=''
+    str_inst_ipv6_dns_search=''
+    str_requested_ipv6=''
+    str_requested_ipv6_prefix=''
+    install_nic_is_ipv6=0
     if [ "$str_os_type" = "aix" ];then
         log_error "configeth on $NODE: aix does not support -s flag"
         exit 1
@@ -643,7 +799,16 @@ elif [ "$1" = "-s" ];then
         fi
     fi
     if [ -n "$IPADDR" ];then
-        str_inst_ip=$IPADDR
+        if [[ "$IPADDR" == *:* ]]; then
+            str_requested_ipv6=${IPADDR%/*}
+            if [[ "$IPADDR" == */* ]]; then
+                str_requested_ipv6_prefix=${IPADDR##*/}
+            fi
+            str_inst_ip=''
+            str_inst_mask=''
+        else
+            str_inst_ip=$IPADDR
+        fi
     fi
 
     if [ -n "$MACADDRESS" ];then
@@ -653,20 +818,38 @@ elif [ "$1" = "-s" ];then
         str_inst_mac=`ip link show $netdev | grep ether | awk '{print $2}'`
     fi
     if [ -z "$str_inst_ip" -o -z "$str_inst_mask" ];then
-        log_info "configeth on $NODE: config install nic, can not find information from dhcp lease file, return."
-        exit 1
-    fi
-    str_inst_net=$(v4calcnet $str_inst_ip $str_inst_mask)
-    num_index=1
-    while [ $num_index -le $NETWORKS_LINES ];do
-        eval str_tmp=\$NETWORKS_LINE$num_index
-        str_tmp_name=`echo $str_tmp | awk -F'net=' '{print $2}' | awk -F'|' '{print $1}'`
-        if [ "$str_tmp_name" = "$str_inst_net" ];then
-            str_inst_mtu=`echo $str_tmp | awk -F'mtu=' '{print $2}' | awk -F'|' '{print $1}'`
-            break
+        # EL10 uses NetworkManager's internal DHCPv6 client, so there may be no
+        # dhclient lease file.  Recover the live global address and its route
+        # metadata before replacing the installer-created connection.
+        if [ "$str_os_type" = "redhat" ] && \
+            [[ $networkmanager_active -eq 1 || $networkmanager_active -eq 2 ]] && \
+            discover_install_nic_ipv6 "$str_inst_nic" "$str_requested_ipv6"; then
+            [ -n "$str_requested_ipv6" ] && str_inst_ipv6=$str_requested_ipv6
+            [ -n "$str_requested_ipv6_prefix" ] && str_inst_ipv6_prefix=$str_requested_ipv6_prefix
+            if [ -n "$str_inst_ipv6" ] && [ -n "$str_inst_ipv6_prefix" ]; then
+                install_nic_is_ipv6=1
+            fi
         fi
-        num_index=$((num_index+1))
-    done
+
+        if [ $install_nic_is_ipv6 -ne 1 ]; then
+            log_info "configeth on $NODE: config install nic, can not find active IPv4 or IPv6 address information, return."
+            exit 1
+        fi
+    fi
+
+    if [ $install_nic_is_ipv6 -ne 1 ]; then
+        str_inst_net=$(v4calcnet $str_inst_ip $str_inst_mask)
+        num_index=1
+        while [ $num_index -le $NETWORKS_LINES ];do
+            eval str_tmp=\$NETWORKS_LINE$num_index
+            str_tmp_name=`echo $str_tmp | awk -F'net=' '{print $2}' | awk -F'|' '{print $1}'`
+            if [ "$str_tmp_name" = "$str_inst_net" ];then
+                str_inst_mtu=`echo $str_tmp | awk -F'mtu=' '{print $2}' | awk -F'|' '{print $1}'`
+                break
+            fi
+            num_index=$((num_index+1))
+        done
+    fi
 
 
     #get extra configration parameters for each nic
@@ -758,28 +941,51 @@ elif [ "$1" = "-s" ];then
     
         #write ifcfg-* file for redhat
         con_name="xcat-"${str_inst_nic}
-        str_inst_prefix=$(v4mask2prefix ${str_inst_mask})
+        if [ $install_nic_is_ipv6 -ne 1 ]; then
+            str_inst_prefix=$(v4mask2prefix ${str_inst_mask})
+        fi
         str_conf_file="/etc/sysconfig/network-scripts/ifcfg-${str_inst_nic}"
         if [ $networkmanager_active -eq 2 ]; then
             str_conf_file="/etc/sysconfig/network-scripts/ifcfg-$con_name"
         fi
-        if [ $networkmanager_active -eq 1 ]; then
+        if [ $install_nic_is_ipv6 -eq 1 ] && [ $networkmanager_active -eq 2 ]; then
+            str_keyfile="/etc/NetworkManager/system-connections/${con_name}.nmconnection"
+            configure_install_nic_ipv6_keyfile "$con_name" "$str_inst_nic" \
+                "$str_inst_ipv6" "$str_inst_ipv6_prefix" \
+                "$str_inst_ipv6_gateway" "$str_inst_ipv6_dns" \
+                "$str_inst_ipv6_dns_search" "$str_inst_mtu" "$str_keyfile"
+            if [ $? -ne 0 ]; then
+                log_error "configeth on $NODE: failed to persist the IPv6 install NIC keyfile."
+                error_code=1
+            fi
+        elif [ $networkmanager_active -eq 1 ]; then
             is_nmcli_connection_exist "$con_name"
             if [ $? -eq 0 ]; then
                 tmp_con_name=${str_inst_nic}"-tmp"
                 nmcli con modify $con_name connection.id $tmp_con_name
             fi
-            if [ -z "$str_inst_gateway" ]; then
-                # EL10/NM: during updatenode the dhclient lease and MACADDRESS may be
-                # absent, leaving the gateway empty. Recover it from the live default
-                # route so the install NIC keeps its default route.
-                str_inst_gateway=`ip route show default | awk '{print $3}' | head -1`
+            if [ $install_nic_is_ipv6 -eq 1 ]; then
+                configure_install_nic_ipv6_nm "$con_name" "$str_inst_nic" \
+                    "$str_inst_ipv6" "$str_inst_ipv6_prefix" \
+                    "$str_inst_ipv6_gateway" "$str_inst_ipv6_dns" \
+                    "$str_inst_ipv6_dns_search" "$str_inst_mtu"
+                if [ $? -ne 0 ]; then
+                    log_error "configeth on $NODE: failed to persist the IPv6 install NIC connection."
+                    error_code=1
+                fi
+            else
+                if [ -z "$str_inst_gateway" ]; then
+                    # EL10/NM: during updatenode the dhclient lease and MACADDRESS may be
+                    # absent, leaving the gateway empty. Recover it from the live default
+                    # route so the install NIC keeps its default route.
+                    str_inst_gateway=`ip route show default | awk '{print $3}' | head -1`
+                fi
+                gw4_arg=""
+                # Never pass an empty gw4: nmcli rejects "value for 'gw4' is missing", the
+                # connection is not created, and the later down+reload leaves the NIC down.
+                [ -n "$str_inst_gateway" ] && gw4_arg="gw4 $str_inst_gateway"
+                nmcli con add type ethernet con-name $con_name ifname ${str_inst_nic} ipv4.method manual ipv4.addresses  ${str_inst_ip}/${str_inst_prefix} connection.autoconnect-priority 9 $gw4_arg
             fi
-            gw4_arg=""
-            # Never pass an empty gw4: nmcli rejects "value for 'gw4' is missing", the
-            # connection is not created, and the later down+reload leaves the NIC down.
-            [ -n "$str_inst_gateway" ] && gw4_arg="gw4 $str_inst_gateway"
-            nmcli con add type ethernet con-name $con_name ifname ${str_inst_nic} ipv4.method manual ipv4.addresses  ${str_inst_ip}/${str_inst_prefix} connection.autoconnect-priority 9 $gw4_arg
             str_conf_file_1="/etc/sysconfig/network-scripts/ifcfg-xcat-${str_inst_nic}-1"
             if [ -f $str_conf_file_1 ]; then
                 grep $con_name $str_conf_file_1 >/dev/null 2>/dev/null
@@ -802,25 +1008,25 @@ elif [ "$1" = "-s" ];then
               echo "GATEWAY=${str_inst_gateway}" >> $str_conf_file
             fi
         fi
-        if [ $networkmanager_active -eq 2 ]; then
+        if [ $install_nic_is_ipv6 -ne 1 ] && [ $networkmanager_active -eq 2 ]; then
             echo "AUTOCONNECT_PRIORITY=9" >> $str_conf_file
         fi
-        if [ -n "${str_inst_dns}" ];then
-	        if [ $networkmanager_active -eq 1 ]; then
-		        nmcli con modify $con_name ipv4.dns ${str_inst_dns}
-                fi
+        if [ $install_nic_is_ipv6 -ne 1 ] && [ -n "${str_inst_dns}" ];then
+            if [ $networkmanager_active -eq 1 ]; then
+                nmcli con modify $con_name ipv4.dns ${str_inst_dns}
+            fi
         fi
-        if [ -n "${str_inst_dns_search}" ];then
-	        if [ $networkmanager_active -eq 1 ]; then
-		        nmcli con modify $con_name ipv4.dns-search "${str_inst_dns_search}"
-                fi
+        if [ $install_nic_is_ipv6 -ne 1 ] && [ -n "${str_inst_dns_search}" ];then
+            if [ $networkmanager_active -eq 1 ]; then
+                nmcli con modify $con_name ipv4.dns-search "${str_inst_dns_search}"
+            fi
         fi
-        if [ -n "${str_inst_mtu}" ];then
-	        if [ $networkmanager_active -eq 1 ]; then
-		        nmcli con modify $con_name mtu ${str_inst_mtu}
+        if [ $install_nic_is_ipv6 -ne 1 ] && [ -n "${str_inst_mtu}" ];then
+            if [ $networkmanager_active -eq 1 ]; then
+                nmcli con modify $con_name mtu ${str_inst_mtu}
             else
                 echo "MTU=${str_inst_mtu}" >> $str_conf_file
-	        fi
+            fi
         fi
 
         # Add GATEWAY to the network file only if the OS version is RHEL 7.x or below.
@@ -840,7 +1046,11 @@ elif [ "$1" = "-s" ];then
         do
             name="${array_extra_param_names[$i]}"
             value="${array_extra_param_values[$i]}"
-            if [[ "$OSVER" =~ ^(rhel|rhels|alma|almalinux|rocky|centos|ol)(9|1[0-9]) ]]; then
+            if [ $install_nic_is_ipv6 -eq 1 ] && [ $networkmanager_active -eq 2 ]; then
+                # The target-root keyfile already contains the live MTU. Other
+                # nmcli-only properties cannot be applied from Anaconda's chroot.
+                :
+            elif [ $install_nic_is_ipv6 -eq 1 ] || [[ "$OSVER" =~ ^(rhel|rhels|alma|almalinux|rocky|centos|ol)(9|1[0-9]) ]]; then
                 nmcli con modify $con_name $name $value
             else
                 echo "$i: name=$name value=$value"
@@ -869,24 +1079,34 @@ elif [ "$1" = "-s" ];then
 
     if [ "$UPDATENODE" = "1" ] || [ "$NODESETSTATE" = "netboot" ] || [ "$NODESETSTATE" = "statelite" ] || grep "REBOOT=TRUE" /opt/xcat/xcatinfo >/dev/null 2>&1; then
         if_state=0
-        if [ "$str_os_type" = "debian" ];then
-            ifdown --force $str_inst_nic
+        if [ $install_nic_is_ipv6 -eq 1 ] && [ $networkmanager_active -eq 2 ]; then
+            # This keyfile belongs to the target system. Do not tear down the
+            # Anaconda-owned live connection from inside the chroot.
+            log_info "configeth on $NODE: IPv6 install NIC keyfile will take effect on first boot."
         else
-            ip link set dev $str_inst_nic down
-        fi
-        if [ $networkmanager_active -eq 1 ]; then
-            nmcli con modify $con_name ipv4.dns "${NAMESERVERS}"
-            nmcli con reload
-            nmcli con up $con_name
-	    else
-            ifup $str_inst_nic
-        fi
-        if [ $? -ne 0 ]; then
-            if_state=$(wait_for_ifstate $str_inst_nic UP 20 5)
-        fi
-        if [ $if_state -ne 0 ]; then
-            log_error "bring $str_inst_nic up failed."
-            error_code=1
+            if [ "$str_os_type" = "debian" ];then
+                ifdown --force $str_inst_nic
+            else
+                ip link set dev $str_inst_nic down
+            fi
+            if [ $networkmanager_active -eq 1 ]; then
+                if [ $install_nic_is_ipv6 -eq 1 ]; then
+                    [ -n "$NAMESERVERS" ] && nmcli con modify "$con_name" ipv6.dns "$NAMESERVERS"
+                else
+                    nmcli con modify $con_name ipv4.dns "${NAMESERVERS}"
+                fi
+                nmcli con reload
+                nmcli con up $con_name
+	        else
+                ifup $str_inst_nic
+            fi
+            if [ $? -ne 0 ]; then
+                if_state=$(wait_for_ifstate $str_inst_nic UP 20 5)
+            fi
+            if [ $if_state -ne 0 ]; then
+                log_error "bring $str_inst_nic up failed."
+                error_code=1
+            fi
         fi
     fi
     if [ $networkmanager_active -eq 1 ] && [ -n "$tmp_con_name" ]; then
